apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: judge-k8s
build:
  artifacts:
  - image: skaffold-dev:34751/judge-k8s
    ko: {}
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
    - dev/k8s/judge-k8s-webhook.yaml
    - dev/k8s/webhook-server-tls.yaml