apiVersion: v1
kind: Namespace
metadata:
  name: judge-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: judge-test
  labels:
    app: judge-k8s-webhook
  name: judge-k8s-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 1323
      protocol: "TCP"
  selector:
    app: judge-k8s-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: judge-test
  name: judge-k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-k8s-webhook
  template:
    metadata:
      labels:
        app: judge-k8s-webhook
    spec:
      containers:
      - name: judge-k8s-webhook
        image: "skaffold-dev:34751/judge-k8s"
        command:
          - "judge-k8s"
          - "serve"
        args:
          - "--cert=/run/secrets/tls/tls.crt"
          - "--key=/run/secrets/tls/tls.key"
          - "--policy=/run/witness-policy/witness-policy.json"
          - "--port=1323"
          - "--public-key=/run/witness-policy/public-key.pem"
          - "--rekor-server=http://rekor-server.default.svc.cluster.local:8077"
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
        - name: witness-policy
          mountPath: /run/witness-policy
          readOnly: true
        ports:
        - name: http
          containerPort: 1323
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
      - name: witness-policy
        configMap:
          name: witness-policy
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  namespace: judge-test
  name: judge-k8s-webook
webhooks:
  - name: judge-k8s-webhook.judge-test.svc
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Ignore
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVRDYwNE9qazhoV0s1WDV2TC9ocVgwek1pUGFrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXlNREl4TVRFNU5UZ3pORm9YRFRJeU1ETXhNekU1TlRnek5Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBUaWFOSDdaUit1azJ2bFh3Y3htQ1djZllZd2QrTW1mbHBXcgpnblZycjJNRjA0MnlyMzlxMWwyUW91NUlHWUJuVHMvTWZ2MWRaVnZpQlEzaHU3dEY4U3QvWDhLN1hNTm5KSjhPCjRYQWVDOExmZGNsb0RZSTJaeFRIamsySlluMlZlV2dGcmJDTGpHbTFQZEdiYysybm9jcFArQnNuaC9EaHpNSk4KK1M4YkZmTjRnRnpDSEplMk9TYWtUeGJvWGkwdlVxZ1ovUXZtMVo2RkR0bjIyTlBRR2Fpci91ZHlyY3hRT25nQwo4S1E2V0dVeCt5c3RHQ3ZQbGRrMXJrVEVTb2UvRHNNK1VWQytXcWhXdUFWY3BXNzJZVitCMDhtRnJLUHJpOGR5Ck5VdkpzTW5iUG9CU0prWkJBQmNzOHlDMEJNRjBVNFZaeE9HZGI5dmtHNTBtYVkyRDNRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVeEtmakZzTlQ0NDdzcnMzcldmTzZ4cXhlRjBBd0h3WURWUjBqQkJnd0ZvQVV4S2ZqRnNOVAo0NDdzcnMzcldmTzZ4cXhlRjBBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFTZ05TRGZrM3N1NFJTU3ZWcXEzclpUTGVWZ0VHUWNTMHhoSW9QM3NWbUlOQSsrV1M4S20rRGxyZmQ1djQKWFM5aE5kU3lmZkdBK3dKd3dNZm55VWVTQkEvU1FqaUhzNFdDNUg2b1cwN3E3ZEpvZUkwSVc5Z2xqL1I2TkpGVAp1di9ZdkFrWnRrQ0VOc0FMM0s0Zlg2cU80czVXNitzSU1ZdUdaaGZPSktSNndBV0toMW9rbnRhanZCVHNqTUlSCk9ZMEdobUU4QkN3S1I2VENkVDd0VzlKcThQeS9SekE4MEF2Zk40cjBLR2pYV3hqaituZGNNMkU1QVNtYzl0NkYKNVlPNHBsYXFBTEkzNHdWbFc2QS9tb3gwWmJONG9KbVN5elNWVkZIeVNqOGh4MldjMEt5V3EvbXRNbW5ZR1dBSwowY21ZTEY4cG5RUmdxQmtaaUxuR1Jhc1d0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: judge-k8s-webhook
        namespace: judge-test
        path: /mutate
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: judge-test
  name: witness-policy
data:
  witness-policy.json: | 
    {"payload":"ewogICJleHBpcmVzIjogIjIwMjItMTItMTdUMjM6NTc6NDAtMDU6MDAiLAogICJzdGVwcyI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiYnVpbGQiLAogICAgICAiYXR0ZXN0YXRpb25zIjogWwogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvbWF0ZXJpYWwvdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvY29tbWFuZC1ydW4vdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogWwogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgIm5hbWUiOiAidGVzdHBvbGljeSIsCiAgICAgICAgICAgICAgICAgICJtb2R1bGUiOiAiY0dGamEyRm5aU0IwWlhOMGNHOXNhV041Q2dwa1pXNTVXMjF6WjExN0NnbHBibkIxZEM1bGVHbDBZMjlrWlNBaFBTQXdDaUFnSUNCdGMyY2dPajBnSW01dmJpMTZaWEp2SUdWNGFYUWdZMjlrWlNJS2ZRb0taR1Z1ZVZ0dGMyZGRld29KYVc1d2RYUXVZMjFrV3pCZElDRTlJQ0ppWVhOb0lnb2dJQ0FnYlhObklEbzlJQ0ppWVhOb0lHNXZkQ0IxYzJWa0lncDkiCiAgICAgICAgICAgICAgfV0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvcHJvZHVjdC92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLnRlc3RpZnlzZWMuY29tL2F0dGVzdGF0aW9ucy9vY2kvdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJmdW5jdGlvbmFyaWVzIjogWwogICAgICAgIHsKICAgICAgICAgICJwdWJsaWNrZXlpZCI6ICJlZDVhNTY5YTM4MGVlYWMyODg4M2U4Y2Q0ZDYyNDQwNTE1YTAxZWQ5NzIyODZkNmViMTJhNzViZTU0MWYxYjNkIgogICAgICAgIH0KICAgICAgXQogICAgfQogIH0sCiAgInB1YmxpY2tleXMiOiB7CiAgICAiZWQ1YTU2OWEzODBlZWFjMjg4ODNlOGNkNGQ2MjQ0MDUxNWEwMWVkOTcyMjg2ZDZlYjEyYTc1YmU1NDFmMWIzZCI6IHsKICAgICAgImtleWlkIjogImVkNWE1NjlhMzgwZWVhYzI4ODgzZThjZDRkNjI0NDA1MTVhMDFlZDk3MjI4NmQ2ZWIxMmE3NWJlNTQxZjFiM2QiLAogICAgICAia2V5IjogIkxTMHRMUzFDUlVkSlRpQlFWVUpNU1VNZ1MwVlpMUzB0TFMwS1RVTnZkMEpSV1VSTE1sWjNRWGxGUVhWU1FsTjJiV1EyT1M5RU5FUktjRVppUTB4UmJEVk9RbmxRVGtoM2JFdFlPSFJZYzFZeGRsUTNkalE5Q2kwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMUW89IgogICAgfQogIH0KfQ==","payloadType":"https://witness.testifysec.com/policy/v0.1","signatures":[{"keyid":"ed5a569a380eeac28883e8cd4d62440515a01ed972286d6eb12a75be541f1b3d","sig":"kiWp/DKVoK6+0F2cjlc/Xu3VF68/bL72uXV7Y6B3cGr1ftzDibjT0TkkJHp3SYT2XNOwRrFMrKOlQc6jWcWqBg=="}]}
  public-key.pem: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQXVSQlN2bWQ2OS9ENERKcEZiQ0xRbDVOQnlQTkh3bEtYOHRYc1YxdlQ3djQ9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=