apiVersion: v1
kind: Service
metadata:
  labels:
    app: judge-k8s-webhook
  name: judge-k8s-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 1323
      protocol: "TCP"
  selector:
    app: judge-k8s-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-k8s-webhook
  template:
    metadata:
      labels:
        app: judge-k8s-webhook
    spec:
      containers:
      - name: judge-k8s-webhook
        image: "skaffold-dev:34751/judge-k8s"
        args:
          - "--cert=/run/secrets/tls/tls.crt"
          - "--key=/run/secrets/tls/tls.key"
          - "--debug"
          - "--policy=/run/witness-policy/witness-policy.json"
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
        - name: witness-policy
          mountPath: /run/witness-policy
          readOnly: true
        ports:
        - name: http
          containerPort: 1323
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
      - name: witness-policy
        configMap:
          name: witness-policy
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: judge-k8s-webook
webhooks:
  - name: judge-k8s-webhook.default.svc
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Ignore
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVSFYwVUc1dWxSZytjeWUveG1RODl4MkthVzRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXlNREV5TmpFMk1qY3lNVm9YRFRJeU1ESXlOVEUyTWpjeU1Wb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXpFVDlobXlnVkIrd1U2Z2lLa2h6U0FvV0I1dFdNb3ZDZlhuVwpXQTVMYlNQdjNBZTFiQk5HVFo4WWF4N3pPRFk0UXBTTHovc1BnSkFqTU9CKzYxbk1ZUTdNYlBhblR4YndnU2tmCjVPbzlpVHBWUTE1ZkRoZXBaOXlkU05XM1BMalc4dWhNOGw4Q3FFOFpIYjBDZ3p0TERmZ0I1NzZ4eXM0NHpzZUwKNk1ka1RjdEo1ZE9FZU9TTE91TUNaWDhpc0JkYVVKYzE2WU1qWDM3Z0EzbkFqQWtVWXhuQWE0T0o1UVRBa2pBNwpsMCtybkZNYVZmQnB5d1NxdVFNaU5veEhjR0IzWkk2ck04WkJCRXl4R05HNEc1SCsrVEVpRXpDTmdFTkNSeG9qClNaMEo5M2ZlL2lack1VUC9pbGQvNTRqQmVaL2NlYW1lMkJieE5UL2NrU0tHSmxjYy93SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVMDh0SmF3aVBQUGtzaFZUZDd6SUZqazNxbGNNd0h3WURWUjBqQkJnd0ZvQVUwOHRKYXdpUApQUGtzaFZUZDd6SUZqazNxbGNNd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFZN3hyZ0pPMk10ckhxT0xLbU1mYXVBQnpqQ1dtalQxL2ZIV1ZTeGYwUlVzMUhhQVk0SXFBaytYanFIYXYKa3JRREpRVEUwUU93am5DSmZOWGpJRWQzeS9GQ3F0Y0hsZ3FxbUlUMkk0MTJ4TkpRb2VIRkFpaVd6SnBodnhwWgpnVWZaWWlmdEhBN1BmMDdiRnN6cE9hVGFUWi91NVR1OFNUL2l6MVA2RVVaSndyOUo3cFV4bnhkQ3hFZkFpK2NOCmhtQlJCbHh4OUVCWWlWTzVzenZHMVBjUjNBb25tRDQzZm5DSk1Qay95YllrUktLaHVsaHlWeFV1R1hQL0kxNHoKTDVrYzJqU2JoQ3M1L3llQUxDN1c2amhCNTZWV294MGQ4U0xPdHg3Nit4eFFvSlhIRVhmR3c1OWprREIySU43RwoyWW83c2FVeGlsZkIycmFiK2NYdW8vNGFNUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: judge-k8s-webhook
        namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: witness-policy
data:
  witness-policy.json: | 
    {"payload":"CnsKICAgICJleHBpcmVzIjogIjIwMjItMTItMTdUMjM6NTc6NDAtMDU6MDAiLAogICAgInN0ZXBzIjogewogICAgICAiYnVpbGQiOiB7CiAgICAgICAgIm5hbWUiOiAiYnVpbGQiLAogICAgICAgICJhdHRlc3RhdGlvbnMiOiBbCiAgICAgICAgICB7CiAgICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvbWF0ZXJpYWwvdjAuMSIsCiAgICAgICAgICAgICJwb2xpY2llcyI6IFtdCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICAidHlwZSI6ICJodHRwczovL3dpdG5lc3MudGVzdGlmeXNlYy5jb20vYXR0ZXN0YXRpb25zL2NvbW1hbmQtcnVuL3YwLjEiLAogICAgICAgICAgICAicG9saWNpZXMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgIHsKICAgICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLnRlc3RpZnlzZWMuY29tL2F0dGVzdGF0aW9ucy9wcm9kdWN0L3YwLjEiLAogICAgICAgICAgICAicG9saWNpZXMiOiBbXQogICAgICAgICAgfQogICAgICAgIF0sCiAgICAgICAgImZ1bmN0aW9uYXJpZXMiOiBbCiAgICAgICAgICB7CiAgICAgICAgICAgICJwdWJsaWNrZXlpZCI6ICJhZTJkY2M5ODllYTljMTA5YTM2ZThlYmE1YzRiYzE2ZDhmYWZjZmU4ZTFhNjE0MTY0NjcwZDUwYWVkYWNkNjQ3IgogICAgICAgICAgfQogICAgICAgIF0KICAgICAgfQogICAgfSwKICAgICJwdWJsaWNrZXlzIjogewogICAgICAiYWUyZGNjOTg5ZWE5YzEwOWEzNmU4ZWJhNWM0YmMxNmQ4ZmFmY2ZlOGUxYTYxNDE2NDY3MGQ1MGFlZGFjZDY0NyI6IHsKICAgICAgICAia2V5aWQiOiAiYWUyZGNjOTg5ZWE5YzEwOWEzNmU4ZWJhNWM0YmMxNmQ4ZmFmY2ZlOGUxYTYxNDE2NDY3MGQ1MGFlZGFjZDY0NyIsCiAgICAgICAgImtleSI6ICJMUzB0TFMxQ1JVZEpUaUJRVlVKTVNVTWdTMFZaTFMwdExTMEtUVU52ZDBKUldVUkxNbFozUVhsRlFXWXlPVzlRVURoVloyaENlVWM0TlRKMVFtUlBlSEpLUzB0dU4wMU5OV2hVWWxBNVpYTm5UMW92YXpBOUNpMHRMUzB0UlU1RUlGQlZRa3hKUXlCTFJWa3RMUzB0TFFvPSIKICAgICAgfQogICAgfQogIH0=","payloadType":"https://witness.testifysec.com/policy/v0.1","signatures":[{"keyid":"ae2dcc989ea9c109a36e8eba5c4bc16d8fafcfe8e1a614164670d50aedacd647","sig":"zAifH+7qT04KxDPXAa86XDgh1tvGMRaYj9ffv0TdhmWOmp6YkgJkN3d+CSJTBsxGavp3ijflBHWt9hsE/JOoAg=="}]}