apiVersion: v1
kind: Namespace
metadata:
  name: judge-test
---
apiVersion: v1
kind: Service
metadata:
  namespace: judge-test
  labels:
    app: judge-k8s-webhook
  name: judge-k8s-webhook
spec:
  ports:
    - name: https
      port: 443
      targetPort: 1323
      protocol: "TCP"
  selector:
    app: judge-k8s-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: judge-test
  name: judge-k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-k8s-webhook
  template:
    metadata:
      labels:
        app: judge-k8s-webhook
    spec:
      containers:
      - name: judge-k8s-webhook
        image: "skaffold-dev:34751/judge-k8s"
        command:
          - "judge-k8s"
          - "serve"
        args:
          - "--cert=/run/secrets/tls/tls.crt"
          - "--key=/run/secrets/tls/tls.key"
          - "--policy=/run/witness-policy/witness-policy.json"
          - "--port=1323"
          - "--public-key=/run/witness-policy/public-key.pem"
          - "--rekor-server=http://rekor-server.default.svc.cluster.local:8077"
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
        - name: witness-policy
          mountPath: /run/witness-policy
          readOnly: true
        ports:
        - name: http
          containerPort: 1323
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
      - name: witness-policy
        configMap:
          name: witness-policy
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  namespace: judge-test
  name: judge-k8s-webook
webhooks:
  - name: judge-k8s-webhook.judge-test.svc
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Ignore
    sideEffects: None
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVRUpySzhBbHZ6WUJocnFRaXByZTdxMjA4aG5rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXlNREl3TWpJeE16WXdNMW9YRFRJeU1ETXdOREl4TXpZd00xb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW1nZHUrc0NobUZyRnlHSkNaZDBVakMxV3pLNGVLL3NNYW0zQQpuakpxSlBlVFV3YkxQVGdPYW4zZjZBQXAva0VVcTdyb0VlNXc5bm5XNXBobkVTY0FkMEZSL2J1M1FReXlOVFV3Ck5tM0JhamgxT2JHbXJVei9qUVYxY1lKR2tHK2FMTFg5NHZLcXUrSU85eDAyQnN3ZjBvV1JXNDl2aktNaXErWXIKSURXWVBueXM5RE0vU3djM2FDUFdkbm1OT3FENDB5WlVSMG9wN1hZWVdvY1o2VS85N2l1TnlJRXRGSThjMjJiTApkTWNvd1ZJZGowaCtTbWk2U2FDTVBOV1NhWGU3bmgrREIwSmlCVldCeUpyRGlIQnQxUlF2TGdxalAwTEVHS002Cnh0MkR3Y21rSTg1ajZSR2o4K1dHSS96Y3VUdlpVdXVSQ3RzTnBTRkdISHRwMmlETGF3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVU1VIc3pkcUE1QkZwMHloR0szWkVPZ2VrUFA0d0h3WURWUjBqQkJnd0ZvQVVTVUhzemRxQQo1QkZwMHloR0szWkVPZ2VrUFA0d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFMeERkVUt5UXhGQjFMZUFMMjN6cTdYckp2UFU2QVp3MlZGVTJjRFEyQVNGY1FkeGQxMVJZU0QwWFBOcWgKdExxL05vT3JaMDFIUGY0aUhzMDFxeUwzOUEwZVNBOUFWc1VBdjdieWFrdzFESXRIWG5ZM1FtbmpFS1Y3TlFodwo4d0duYVJZeVFidWJNdFoySWtRcndzTjZ1bDBLdHo5R1B0YjVic056ZnUwbFdmWTV3MVVKNzhOUWExTmlZVmxxCmRBV0JKN1VZVkxpbTQ0aDNuMUNocWxKbHU3NUR1VUU1Q3hDMzRSRytZTVBxNkpQVnBSM1YyVDlLelJKWUtGd04KeXNoQWQxUm50RWEyU2RXWDBKMkpFNW9TeUJCUlZIQ2JaTUZuTll1TjNhS3BWWWlLTzhqaElkdm9mV0thNitReQpkYUxaaUJaSnNlcjhyTER2d0FFQlI4Qkxndz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: judge-k8s-webhook
        namespace: judge-test
        path: /mutate
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: judge-test
  name: witness-policy
data:
  witness-policy.json: '{"payload":"ewogICJleHBpcmVzIjogIjIwMjItMTItMTdUMjM6NTc6NDAtMDU6MDAiLAogICJzdGVwcyI6IHsKICAgICJidWlsZCI6IHsKICAgICAgIm5hbWUiOiAiYnVpbGQiLAogICAgICAiYXR0ZXN0YXRpb25zIjogWwogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvbWF0ZXJpYWwvdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvY29tbWFuZC1ydW4vdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogWwogICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgIm5hbWUiOiAidGVzdHBvbGljeSIsCiAgICAgICAgICAgICAgICAgICJtb2R1bGUiOiAiY0dGamEyRm5aU0IwWlhOMGNHOXNhV041Q2dwa1pXNTVXMjF6WjExN0NnbHBibkIxZEM1bGVHbDBZMjlrWlNBaFBTQXdDaUFnSUNCdGMyY2dPajBnSW01dmJpMTZaWEp2SUdWNGFYUWdZMjlrWlNJS2ZRb0taR1Z1ZVZ0dGMyZGRld29KYVc1d2RYUXVZMjFrV3pCZElDRTlJQ0ppWVhOb0lnb2dJQ0FnYlhObklEbzlJQ0ppWVhOb0lHNXZkQ0IxYzJWa0lncDkiCiAgICAgICAgICAgICAgfV0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogImh0dHBzOi8vd2l0bmVzcy50ZXN0aWZ5c2VjLmNvbS9hdHRlc3RhdGlvbnMvcHJvZHVjdC92MC4xIiwKICAgICAgICAgICJyZWdvcG9saWNpZXMiOiBbXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiaHR0cHM6Ly93aXRuZXNzLnRlc3RpZnlzZWMuY29tL2F0dGVzdGF0aW9ucy9vY2kvdjAuMSIsCiAgICAgICAgICAicmVnb3BvbGljaWVzIjogW10KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJmdW5jdGlvbmFyaWVzIjogWwogICAgICAgIHsKICAgICAgICAgICJwdWJsaWNrZXlpZCI6ICJhZTJkY2M5ODllYTljMTA5YTM2ZThlYmE1YzRiYzE2ZDhmYWZjZmU4ZTFhNjE0MTY0NjcwZDUwYWVkYWNkNjQ3IgogICAgICAgIH0KICAgICAgXQogICAgfQogIH0sCiAgInB1YmxpY2tleXMiOiB7CiAgICAiYWUyZGNjOTg5ZWE5YzEwOWEzNmU4ZWJhNWM0YmMxNmQ4ZmFmY2ZlOGUxYTYxNDE2NDY3MGQ1MGFlZGFjZDY0NyI6IHsKICAgICAgImtleWlkIjogImFlMmRjYzk4OWVhOWMxMDlhMzZlOGViYTVjNGJjMTZkOGZhZmNmZThlMWE2MTQxNjQ2NzBkNTBhZWRhY2Q2NDciLAogICAgICAia2V5IjogIkxTMHRMUzFDUlVkSlRpQlFWVUpNU1VNZ1MwVlpMUzB0TFMwS1RVTnZkMEpSV1VSTE1sWjNRWGxGUVdZeU9XOVFVRGhWWjJoQ2VVYzROVEoxUW1SUGVISktTMHR1TjAxTk5XaFVZbEE1WlhOblQxb3ZhekE5Q2kwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMUW89IgogICAgfQogIH0KfQ==","payloadType":"https://witness.testifysec.com/policy/v0.1","signatures":[{"keyid":"ae2dcc989ea9c109a36e8eba5c4bc16d8fafcfe8e1a614164670d50aedacd647","sig":"DOtx+PDHmxmc6PVAON4H+U9sv1aqhVRYmc/Bud6TIIM57qmXQJ0idc0F66Sz9dlXyfoU0o9gH1e8iRGdBZBNDA=="}]}'
  public-key.pem: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAf29oPP8UghByG852uBdOxrJKKn7MM5hTbP9esgOZ/k0=
    -----END PUBLIC KEY-----
