kind: Service
apiVersion: v1
metadata:
  name: logserver-service
  labels:
    app: trillian-log-server
spec:
  selector:
    app: trillian-log-server
  ports:
  - name: grpc
    port: 8080
    targetPort: 8090
  - name: http
    port: 8091
    targetPort: 8091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trillian-log-server
  name: trillian-log-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillian-log-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trillian-log-server
    spec:
      containers:
      - image: gcr.io/trillian-opensource-ci/log_server:latest
        name: log-server
        args:
          - "--storage_system=mysql"
          - "--mysql_uri=root:root@tcp(mysql)/rekor"
          - "--rpc_endpoint=0.0.0.0:8090"
          - "--http_endpoint=0.0.0.0:8091"
          - "--alsologtostderr"
        ports:
          - containerPort: 8090
            name: grpc
          - containerPort: 8091
            name: http